### ISSUE TITLE
Error when running your tool

### ISSUE THREAD

**Issue by dmc1778** [ise-uiuc/DeepREL#2]
Hi, I have the following error when running DeepREL
`Traceback (most recent call last):
  File "DeepREL.py", line 2, in <module>
    from classes.torch_api import TorchAPI
  File "/media/nimashiri/DATA/vsprojects/DeepREL/pytorch/src/classes/torch_api.py", line 3, in <module>
    from classes.argdef import ArgDef
  File "/media/nimashiri/DATA/vsprojects/DeepREL/pytorch/src/classes/argdef.py", line 6, in <module>
    class ArgDef:
  File "/media/nimashiri/DATA/vsprojects/DeepREL/pytorch/src/classes/argdef.py", line 45, in ArgDef
    def args_similar(self, args: list['ArgDef'], w_name=0.3, w_type=0.7):
TypeError: 'type' object is not subscriptable
`

**Comment by YangChenyuan** [comment]
Hi @nimashiri, which python version do you use? 

I recommend you use python 3.9 if not :)

**Comment by dmc1778** [comment]
Thanks Yang, This is my python
`Python 3.8.10 (default, Jun 22 2022, 20:18:18) `

**Comment by YangChenyuan** [comment]
Python 3.8 doesn't support some type annotation. It would be better to use Python 3.9. Otherwise, you maybe need to delete such annotation `list['class']` manually.

**Comment by dmc1778** [comment]
OK thanks Yang

**Comment by YangChenyuan** [comment]
You're welcome. Hope this solves your problem :)
